### ISSUE TITLE
backface visibility 

### ISSUE THREAD

**Issue by artistneel** [WonderMediaProductions/Maya2glTF#41] opened 2018-08-19 06:46 UTC
I didnt find any option to make the backface visible in maya gltf shader, can you help

**Comment by Ziriax** [comment] 2018-08-19 09:36
It is not yet part of the shader, see #34 why.

Basically backface culling is defined on a mesh in Maya, but on a shader in GLTF. Furthermore the Maya default value is to not cull backfaces, certainly not the right default value for GLTF.

That being said, I plan to release a new version this week that at least contains a dummy checkbox in the shader to set this.

Closing this as a duplicate of #34

**Closed by Ziriax** 2018-08-19 09:36 UTC
