### ISSUE TITLE
Multiple errors recieved - Could not complete  

### ISSUE THREAD

**Issue by SolBlair86** [WonderMediaProductions/Maya2glTF#127] opened 2020-06-24 22:20 UTC
Hi guys,

as requested, I've received these errors below. Any suggestions on how to resolve this? 

HEAD is now at 17764bb Make sequence_equal compatible with order_by
[ 38%] No patch step for 'linq'
[ 39%] Performing update step for 'linq'
[ 40%] No configure step for 'linq'
[ 42%] No build step for 'linq'
[ 43%] No install step for 'linq'
[ 45%] Completed 'linq'
[ 45%] Built target linq
Scanning dependencies of target maya2glTF
[ 46%] Building CXX object CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:52:9: error: 
      redefinition of 'path'
                class path {
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:738:24: note: 
      previous definition is here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:690:15: error: 
      redefinition of 'create_directory'
                inline bool create_directory(const path &p) {
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1554:39: note: 
      previous definition is here
inline _LIBCPP_INLINE_VISIBILITY bool create_directory(const path& __p) {
                                      ^
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:694:19: error: 
      no member named 'str' in 'std::__1::__fs::filesystem::path'
                        return mkdir(p.str().c_str(), S_IRUSR | S_IWUSR ...
                                     ~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:711:29: error: 
      no member named 'getcwd' in 'std::__1::__fs::filesystem::path'
                                m_paths.push_back(path::getcwd());
                                                  ~~~~~~^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:753:19: error: 
      no member named 'exists' in 'std::__1::__fs::filesystem::path'
                                        if (combined.exists()) {
                                            ~~~~~~~~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:782:15: error: 
      redefinition of 'create_directories'
                inline bool create_directories(const path& p)
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1545:39: note: 
      previous definition is here
inline _LIBCPP_INLINE_VISIBILITY bool create_directories(const path& __p) {
                                      ^
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:784:13: error: 
      no member named 'make_absolute' in 'std::__1::__fs::filesystem::path'
                        return p.make_absolute().mkdirp();
                               ~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:787:15: error: 
      redefinition of 'temp_directory_path'
                inline path temp_directory_path()
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1926:39: note: 
      previous definition is here
inline _LIBCPP_INLINE_VISIBILITY path temp_directory_path() {
                                      ^
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:800:15: error: 
      redefinition of 'exists'
                inline bool exists(const path& path)
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1614:39: note: 
      previous definition is here
inline _LIBCPP_INLINE_VISIBILITY bool exists(const path& __p) {
                                      ^
In file included from /Users/solomonblair/Documents/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/solomonblair/Documents/Maya2glTF/src/filesystem.h:11:
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:802:16: error: 
      no member named 'exists' in 'std::__1::__fs::filesystem::path'
                        return path.exists();
                               ~~~~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:813:36: error: 
      no member named 'type' in 'std::__1::__fs::filesystem::path'
                        hash_combine(seed, (size_t)path.type);
                                                   ~~~~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:814:28: error: 
      no member named 'absolute' in 'std::__1::__fs::filesystem::path'
                        hash_combine(seed, path.absolute);
                                           ~~~~ ^
/Users/solomonblair/Documents/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:816:32: error: 
      no member named 'leafs' in 'std::__1::__fs::filesystem::path'
                        for (const string &s : path.leafs) {
                                               ~~~~ ^
13 errors generated.
make[2]: *** [CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o] Error 1
make[1]: *** [CMakeFiles/maya2glTF.dir/all] Error 2
make: *** [all] Error 2
solomonblair@Solomons-iPro Maya2glTF %

**Comment by Ziriax** [comment] 2020-06-24 22:30
You seem to be using a version of xcode that finally comes with std filesystem...

At the time Maya2glTF was ported to MacOS, it didn't have those classes yet.

Could you give me:
- the branch and revision your are building (I guess latest commit in develop branch?)
- the version of MacOS 
- the version of Xcode
- the version of Maya

I will look into this

**Comment by Ziriax** [comment] 2020-06-24 22:40
Ah, our code might be using a version of the filesystem stub that is too old.

In the CMakeFile.txt, can you try to change:


```cmake
# filesystem
ExternalProject_Add(filesystem
  GIT_REPOSITORY https://github.com/gulrak/filesystem
  GIT_TAG v1.2.6
  PREFIX filesystem
  INSTALL_DIR
  CMAKE_ARGS
	-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_COMMAND ""
)
``` 

To `GIT_TAG v1.3.2`

And then delete the `build` folder, and build again from scratch?

**Comment by SolBlair86** [comment] 2020-06-25 18:49
Hi Peter,

my apologies for the delay and I greatly appreciate your attention here. A
problem I have now is I no longer have access to Maya 2018, only Maya 2020.
I have tried this with 2020 but the directories seem to be a hang up. I am
somewhat of a noob here, and not sure if this is possible for 2020?

Error:

-- Configuring incomplete, errors occurred!

See also
"/Users/solomonblair/Documents/Maya2glTF/build/CMakeFiles/CMakeOutput.log".

solomonblair@Solomons-iPro Maya2glTF %


**ATTACHED OUTPUT LOG* *

NOTES ON MY VERSIONS:
Formerly testing with Maya 2018, now testing with Maya 2020
MacOS 10.15.5 (19F101
XCode Version 11.5 (11E608c)


Again, thank you.

Solomon

**Comment by Ziriax** [comment] 2020-06-25 19:45
I will try to reproduce this, and get back to you. If all goes well, I'll attach a binary version for you here.

**Comment by Ziriax** [comment] 2020-06-26 08:36
Well, my Mac got screwed up when upgrading to a newer version of MacOS, so this is going to take a while...

**Comment by Ziriax** [comment] 2020-06-26 11:46
Phew, got it installed, building now... I'll keep you posted.

**Comment by Ziriax** [comment] 2020-06-26 12:22
The latest `develop` branch seems to work fine for Maya 2020.

I've attached my complete `/Users/Shared/Autodesk/maya` folder, so in theory, you can extract the attached [maya.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/4836858/maya.zip) file to `/Users/Shared/Autodesk`, restart Maya,  and execute the MEL command `maya2glTF_UI`, and all should work.

If that **_doesn't work_**, you can try to build from the sources:

1. Open a terminal window
2. If you already cloned `Maya2glTF` with `git`, delete the folder you cloned it in.
3. `git clone -b develop https://github.com/WonderMediaProductions/Maya2glTF ~/Documents/Maya2glTF`
4. `cd ~/Documents/Maya2glTF`
5. `./osx_create_project 2020`
6. `cd build`
7. `make install`

If that all works, the plugin should be available in Maya. Restart Maya, and execute the MEL command `maya2glTF_UI`

Please let me know what steps work or don't work for you.

Happy exporting!

**Comment by Ziriax** [comment] 2020-06-28 21:37
Closing because no feedback

**Closed by Ziriax** 2020-06-28 21:37 UTC
