### ISSUE TITLE
don't give up, the world needs your work :P

### ISSUE THREAD

**Issue by reduz** [WonderMediaProductions/Maya2glTF#1] opened 2017-11-21 21:09 UTC
in any case, if you need help, we can test your work with Godot as soon as you have something going.

**Comment by pjcozzi** [comment] 2017-11-21 21:12
@reduz - @Ziriax has been making a ton of progress everyday; check out: https://github.com/Ziriax/Maya2glTF/commits/develop

**Comment by Ziriax** [comment] 2017-11-21 21:39
@reduz I'm not going to give up, but it will take a while. I believe in glTF. I don't want to just copy/paste old code, I want to try to understand it again, and learn some new C++ in the meantime; I mostly did Haskell, C# and Typescript development that last 10 years, so I had to brush up my old school C++ skills ;-) Currently I'm working on the blend shapes export. Next animation of nodes and blend shape weights. Then skinning, then shading. For future stuff, too bad glTF does not support dual quaternion skinning, no qtangents (or bivectors instead of normals), but not many engines do, so it can be an extension.

**Comment by zellski** [comment] 2017-11-21 23:20
I hear you, @Ziriax. It's amazing how decade in the land of kinder, gentler languages leaves you unprepared for the sheer number of ways C++ allows you to shoot yourself in the foot. I'm curious how many similarities there are between your export work and my FBX->glTF converter. I'm sure FBX mirrors Maya's internals to **some** degree, since it's an Autodesk format...

**Comment by Ziriax** [comment] 2017-11-22 07:51
I am not sure, I don't know FBX. I never felt like looking into it since we
never succeeded to export our characters with it, and it was closed source
(is it open now?)


Actually the latest FBX exporter in Maya 2018 crashes on our characters,
and the Collada exporter takes forever. So it is hard for me to test these
exporters on our characters.

It has been ages since I digged deep in the Maya API and used C++, so yes,
this is an adventure :-)

But I must say the brilliant devs at Jetbrains improved their Resharper C++
support immensely, making C++ development a lot more pleasant than it used
to be. But still far away from the luxury of C# coding.

I could have made a prototype of the exporter in C#, since Maya supports
that now, but then Windows would be the only supported platform, not ideal.

IMO Maya doesn't have a static file format, it is a dataflow program, nodes
can be connected in any way desired. That makes it nasty to make a perfect
exporter. In practice it means it will only work on some common
configuration of nodes. That's why in the CG movie business people use
Alembic point clouds to transfer 3D content between different programs,
that always works, but is not very practical for games ;-)

I am now struggling with triangles being culled incorrectly on some meshes
using the vscode BabylonJS viewer that I use. It works in the ThreeJS
viewer. I can't see it in the Cesium viewer since that one uses a default
material that is flat. But these meshes did display correctly using my
initial versions of the exporter, so I must have broken something. I did
not use Maya's own triangulation in this early versions, now I do. So maybe
the winding is not correct anymore now, or the normals are wrong. To be
debugged today.

**Comment by Ziriax** [comment] 2017-11-22 10:27
Oops, it seems the default BabylonJS material doesn't do depth sorting or something. When adding a dummy material to the scene , the mesh is correct. So the normals were correct after all it seems ;-)

**Comment by zellski** [comment] 2017-11-22 19:19
I've noticed BabylonJS didn't do so well with self-transparency for one of my models; I was accidentally labelling some materials BLEND that should've been OPAQUE, and even though none of the actual triangles were transparent, everything was a jumble. It might've been an edge case of some sort.

You're throwing stuff at the gltf-validator, I assume? That thing is fantastic for sorting out a whole host of problems. Whatever's still busted after that, at least you can be pretty sure it's a more subtle problem. :)

I use JetBrains CLion, actually. It's mostly pretty great, although you can tell that C++ is not as easy a language to refactor as e.g. Java. I didn't realize Resharper might have C++ support... that's interesting.

**Comment by Ziriax** [comment] 2017-11-22 20:08
I do find it strange that the default BabylonJS material seems to assume that the model is transparent... Because of that I lost two days searching for a bug in my code ;-) 

I added some command line arguments to my exporter to generate a default material, and also an debugging  options to assign a material with a different hue for each primitive. 

Yes, I'm using the great glTF validator. Actually I'm using Analytical Graphics, Inc vscode glTF extension, and that's a very handy tool indeed.

We purchased a Resharper subscription years ago, and now it also supports C++. Fantastic tool, it has made coding so much more enjoyable.

**Comment by bghgary** [comment] 2017-12-01 22:24
> I do find it strange that the default BabylonJS material seems to assume that the model is transparent... 

If you still have a repro of this, let me know. Default materials are not supposed to be transparent.

**Comment by Ziriax** [comment] 2017-12-01 23:04
Maybe the default material was not transparent, but it behaves as if it was, in the sense that no or inverse depth sorting was applied. It might still have been an issue with my exporter, but since explicitly creating a default glTF material fixed the depth sorting, I doubt that. I will try to make a repro with a mesh that I am allowed to distribute.

**Comment by bghgary** [comment] 2017-12-19 00:49
We found the issue. See https://github.com/BabylonJS/Babylon.js/issues/3413. We will fix it shortly.

**Comment by Ziriax** [comment] 2017-12-19 09:06
Good news, it means my code wasn't faulty :-)

I haven't been able to work on the exporter the last weeks, due to some internal decisions of my employer. I hope to find more time the coming weeks.

**Comment by sbtron** [comment] 2017-12-21 15:56
Since BabylonJS was mentioned, just wanted to add that the Maya exporter for BabylonJS is also being updated to export glTF - https://github.com/BabylonJS/Exporters/tree/master/Maya 
Its still WIP but please chime in if you think there is a way to collaborate and make the exporter easier to use for glTF. The world certainly needs a good Maya exporter for glTF :)

**Comment by Ziriax** [comment] 2017-12-21 16:09
@sbtron  Nice! I see that the BabylonJS exporter is written in C#, I should have done that too, I would have made a lot more progress like that. On the other hand, C# Maya plugins only work on Windows no?

**Comment by Ziriax** [comment] 2017-12-21 23:21
I made some more progress, I was able to export the WondreMedia tiger character with texturing and correct UVs and normals. However, in the VSCode glTF viewer, it only renders correctly with Three.JS and Cesium, BabylonJS does very strange things with the texture mapping. I will test with publicly available models, and provide screenshots. 

Actually, none of the renderers fully render it correctly, since they don't seem to deal with transparency. At first sight it doesn't seem possible to indicate that a primitive is transparent in glTF 2.0? That is rather important since transparent objects need to be rendered differently in most engines.

**Comment by zellski** [comment] 2017-12-22 18:31
@Ziriax - the primitive references a material, and the material has `alphaMode` which can be `OPAQAUE`, `MASK`, or `BLEND`. I'm pretty sure all the main renderers handle at least the most basic cases of transparency correctly. I think none of them handle vertex colour transparency well (we had to write our own simple shader for this in three.js) and they all do different things in the self-transparent situation, where a primitive has both transparent and opaque parts. But that's a Hard Problem in general, if I understand things correctly.

In FBX2glTF I flag a primitive as `BLEND` if it it has a diffuse/baseColor texture that's backed by a RGBA PNG. I don't actually check the contents of the alpha channel; that's far down on some mental TODO list.

Feel free to drop a .glb with misbehaving transparency, if you want a second pair of eyes on it.

**Comment by Ziriax** [comment] 2017-12-22 20:14
@zellski Thanks for the info! 

However, I can't find the declaration of `alphaMode` in the [glTF 2.0 reference](https://www.khronos.org/files/gltf20-reference-guide.pdf) guide, nor the[ glTF C++ code](https://github.com/KhronosGroup/COLLADA2GLTF/blob/2.0/GLTF/include/GLTFMaterial.h) that I'm using (from  COLLADA2GLTF)

But now I notice that the [markdown glTF spec ](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-textureInfo)does talk about `alphaMode`, and more, so I guess the reference guide and COLLADA2GLTF are not up-to-date with the latest spec.

You could call me rather old-school (so old that I actually made videogames on Commodore home computers, in assembly language, go figure), and yes, I *printed* the reference guide PDF, assuming it was the latest version :wink:

I will just patch the GLTF code from COLLADA2GLTF then, and submit a patch request.

**Comment by zellski** [comment] 2017-12-22 20:23
I think that lovely full-colour poster (which I have also printed out -- I am old-school too) is just not meant to provide every glTF detail. The markdown version you mention is what I use myself when I need an exhaustive description of every wrinkle of the spec.

For what it's worth, there is an up-to-date version of the image [here](https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/gltfOverview-2.0.0a.png) -- but that doesn't mention `alphaMode` either.

**Comment by Ziriax** [comment] 2017-12-22 20:36
Okay, got it. Yes, it is a lovely poster indeed! Maybe good for T-shirts too ;-)

Patching the code as we speak, I'm curious to see the result in vscode. Getting back into 3D after years of front-end coding feels good :)

**Comment by Ziriax** [comment] 2018-03-20 11:06
I'm closing this issue, since the exporter is feature complete for our inhouse usage now, it exports PBR, blend-shapes and skinning, and multiple baked animation clips. 

Of course I must now stabilize the code, make it understandable 😉, add regression tests, maybe unit tests, update the documentation. Then add support for Draco mesh compression, deal with Maya's segment scale compensation, add animation curve compression and quantization, etc... But none of these is essential for our inhouse usage of glTF, so that might take a while.

Thanks for the moral support! 😃

**Comment by zellski** [comment] 2018-03-24 16:04
What are your plans for segment scale compensation? In FBX2glTF there's only so much I can do. The inheritance type is just not available in glTF, and can't really be faked. We could probably bake the scaling factor into all the mesh geometries and eliminate node transforms, but then animations break. I'm curious though if, since you're actually running inside/next to Maya itself, would you be able to actually disable SSS in each model joint before you trigger the export?

**Comment by Ziriax** [comment] 2018-03-24 16:26
Ah yes, segment scale compensation... I forgot about that :) I'll add a test scene for that. I think I can easily solve this by introducing two extra nodes before and after the segment-scale-compensated joint (and only when the scale of the parent joint is not uniform).  I'll make an issue for this. Thanks for reminding me!

I was actually hoping that segment scale compensation would be solved by the more general idea of using Singular Value Decomposition, but that might be much harder. 

Also on my list is adding "logical parents"; our artists often construct rigs with joints that are driven by some other logic. These joints often live in world space, but for exporting, they should be parented to some other joint. In our custom OGRE exporter we use custom attributes for this (overriding the parent).

**Comment by Ziriax** [comment] 2018-03-30 19:04
@zellski I have segment scale compensation working for static meshes, but something goes wrong in the animation, but that's fixable. I've solved it by adding one extra node for carrying the inverse parent scale. I'll keep you posted.

**Comment by JunkYardRobotBoy** [comment] 2018-04-29 15:14
@Ziriax Great work on this plugin. Its amazing and we really appreciate you sharing your hard work! I'm getting stuck when I want to export multiple animation clips to segment the timeline on an export.

**Comment by JunkYardRobotBoy** [comment] 2018-04-29 16:03
@Ziriax Thanks for the reply! The main issue is I don't know how to add multiple arguments for the -acn flags. I've tried a number of loops and functions to pass these in but with no success :(
I'm running this:
maya2glTF -outputFolder "C:/MAMP/htdocs/gltf/models" -sceneName "modelOne" -acn "clipOne" -ast 0 -aet 70 -afr 25;
as a mel command in the script editor, and it works. But if I add another clip or try pass it into an array I get an error: // Error: Line 1.113: Syntax error // 
If you could provide a mel script example that we can run in the script editor that would be greatly appreciated.
However,  I'm also looking into the trax editor now and will publish results if I'm successful! Thanks again

**Comment by Ziriax** [comment] 2018-04-29 16:13
Passing multiple -acn, -ast, -aet flags should work, but I might have broken something. 

You only need to pass -afr once if it's the same for all clips. 

I will debug this ASAP, it must be a silly bug.

Support for Trax is not yet done, but that will purely be done in MEL anyway.

**Comment by Ziriax** [comment] 2018-04-29 17:41
@JunkYardRobotBoy  I can confirm this is broken, fixing it as we speak

**Comment by Ziriax** [comment] 2018-04-30 21:12
@JunkYardRobotBoy I released v0.9.3, maybe this works for you. I did find some other issue, the new test scene 'complex1' I made doesn't seem to export the animation clips correctly; to be debugged.

**Comment by JunkYardRobotBoy** [comment] 2018-07-12 14:49
@Ziriax Was looking for a way to message you directly but as this thread is about thanking you for this amazing plugin, its probably the best place. I wanted to give back a little bit as best I know how. I created a little tutorial video that's about my process of taking a character from Maya into three JS using your plugin - giving you full credit where it as more that due.

Its about the insights gained and problems that I ran into while diving into webXR from an animators point of view. I want to encourage my fellow artists to experiment with this tech and what to look out for and where you can really push things in this exciting web XR space. I'll be placing it on my site when it (Junk Yard Robot Boy) is ready to go live but wanted to see if you're ok with me talking about my experience with this plugin. 

The video is on vimeo now: https://vimeo.com/279657779

**Comment by Ziriax** [comment] 2018-07-12 17:38
@JunkYardRobotBoy Great stuff!!! Many thanks 👍

**Comment by Ziriax** [comment] 2019-09-24 09:09
Closing this first issue that caused many late coding nights :-)

**Closed by Ziriax** 2019-09-24 09:09 UTC
Labels: good first issue
