### ISSUE TITLE
Maya 2018 crashes on macOS Mojave when exporting simple cube polygon

### ISSUE THREAD

**Issue by MartinZenz** [WonderMediaProductions/Maya2glTF#66] opened 2019-01-16 15:56 UTC
I am running Maya 2018 on macOS Mojave.  After selecting all polygons and exporting, the plugin crashes Maya for the attached scene.

[cube.mb.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/2764851/cube.mb.zip)

Let me know if you need any other details.

Best,

**Comment by Ziriax** [comment] 2019-01-16 16:47
Thanks for reporting, I'll look into this.

**Comment by Ziriax** [comment] 2019-01-16 19:32
It seems the quick & dirty replacement of `filesystem` that I hacked together isn't fully working, because it is just the saving that fails for some reason. Because  the exporter is working, it is just the saving of the data that fails (actually it is just creating the directories that crashes). 

The good news is that the [newest LLVM](https://www.phoronix.com/scan.php?page=news_item&px=Filesystem-Lands-LLVM-Libcpp) finally seems to implement this feature, so I will hopefully be able to drop my own filesystem stub, and use the same code as the Windows version for all this.

I'll keep you posted. In the meanwhile, if you have a Windows machine, you could try that.

**Comment by Ziriax** [comment] 2019-01-18 08:04
It seems this is caused by a bug in the COLLADA2GLTF library, not the filesystem code. [I already fixed this bug, and my PR was merged](https://github.com/KhronosGroup/COLLADA2GLTF/commit/34f55fe185a27cf052abd56da54c60b1a7ea4d40), so the bug should be fixed soon.

This might also affect the Windows version.

**Comment by Ziriax** [comment] 2019-01-19 16:41
The latest version in the `cmake` branch should fix this. I will also need to update the Windows version to pick up the bug I fixed in the external GLTF library. Thanks for reporting!

**Closed by Ziriax** 2019-01-19 16:41 UTC
