### ISSUE TITLE
Maya2GLTF PBR Material - Environment maps not being exported 

### ISSUE THREAD

**Issue by Chase-Reid** [WonderMediaProductions/Maya2glTF#33] opened 2018-06-26 21:45 UTC
Hello!

I am having an issue with the maya PBR material. While applying maps to my car body, I have applied the following texture:
![t_cityblock_env](https://user-images.githubusercontent.com/26173435/41940650-5e6ce6ce-794e-11e8-88c0-8c22f4f40e41.jpg)

...to the Environment fields outlined below:
![image](https://user-images.githubusercontent.com/26173435/41940638-547df6f8-794e-11e8-89fb-44d31c7da1a4.png)

I export the object out of maya, but unfortunately, when I import my object into the threejs editor my environment map is empty. 
![image](https://user-images.githubusercontent.com/26173435/41940809-e20a730c-794e-11e8-8697-378ab2e9fe11.png)

Am I using the environment properties incorrectly or is this a bug?

**Comment by Ziriax** [comment] 2018-06-26 22:20
glTF 2.0 files do not specify the environment map. I have just put it in the Maya shader for previewing.

So it is not a bug, it is by design, because I cannot put this in a standard glTF file.

Typically you specify an environment in  your render engine of choice, separate from the 3D models you are importing. It will be the same for all models.

That being said, as soon as Maya2glTF will support the KHR lights extension, environment maps will be exported as part of the lights I guess. Obviously the render engines must also support this extension.

**Comment by Chase-Reid** [comment] 2018-06-26 23:04
Thank you for the reply. I just did a test GLTF export from the ThreeJS editor to debug this issue and I see what you are talking about. Good to know! Feel free to close this issue :)

**Comment by Ziriax** [comment] 2018-06-27 05:33
Thanks for reporting! Getting user feedback is important. Closing this now then :-)

**Closed by Ziriax** 2018-06-27 05:33 UTC
